### ISSUE TITLE
Issue in Google Sync

### ISSUE THREAD

**Issue by JEEVAN28** [joforce/JoForceCRM#115]
When I am trying to connect google contacts, I am facing below issue

It appears you don't have
permission to access this page.
403 Error. Forbidden.
![google_login_01](https://user-images.githubusercontent.com/12723595/78102053-f22eca80-7406-11ea-8346-5040339af20e.JPG)
![google_login_02](https://user-images.githubusercontent.com/12723595/78102057-f5c25180-7406-11ea-91d1-0a3fd9c5b606.JPG)
![google_login_03](https://user-images.githubusercontent.com/12723595/78102064-f8bd4200-7406-11ea-8391-1955b192ea5a.JPG)

**Comment by fenzik** [comment]
https://www.loom.com/share/812e485c965f4a4e880c4faddc01c28b
