### ISSUE TITLE
Outgoing SMTP server error - Mail could not be sent ...

### ISSUE THREAD

**Issue by scotlad9** [joforce/JoforceCRM#117]
Evaluating Joforce 1.5 on VM with Apache2.4, MySQL 5.7 and PHP 5.6.  Trying to configure outgoing server and get error "mail could not be sent ..." with either my Office 365 account or my Gmail account.

Thunderbird email works correctly on this server with either account.

For Office 365 I've tried various settings including tls://office365:587 with 'requires verification' ticked.  This setting works with my Vtiger 7.1 installation.

Can anyone confirm the correct settings for Office 365 (Exchange) and Gmail please.

**Comment by smackrajue** [comment]
Yes, please try these steps 
- Open your Google Admin console (admin.google.com).
- Click Security > Basic settings .
- Under Less secure apps, select Go to settings for less secure apps .
- select the Enforce access to less secure apps for all users radio button. ...
- Click the Save button.

**Comment by smackrajue** [comment]
Also for Office 365,  

**Turning user consent on or off**
- In the admin center, go to the Settings > Org settings > Services page, 
- select User consent to apps.
- select the option to turn user consent on or off.
