### ISSUE TITLE
Can I modify the joforce ?

### ISSUE THREAD

**Issue by uttamsharma** [joforce/JoforceCRM#118]
Hello, you really created a nice product. It is the best fork of vTiger even much better then yetiforce. I believe the open source liceance is much easy then any other. I just want to ask. Like you created the joforce on the core of vtiger. I want to do the following things with joForce.
1. Fork it and give a different name to the forked version. 
2. Modify the UI and some features (minor)
3. Remove the footer. (Credit on a different place or something like powered by joForce on footer )
4. Provide a hosted solution but keep it open source. 
I think the liceance allowed to do these things but just want to make sure from you.
 Is it allowed to do the following things ? 

Thanks for this really awesome project.

**Comment by waistracloud** [comment]
Yes, joForce is the fork of the vtiger, and joForce shares the same license. So you can do this but you should confirm this with one of the developer or contributor in joforce.

**Comment by uttamsharma** [comment]
Why you not replying ? Even at your website if I ask about any commercial query you fired the series of emails. But when ask this question no reply. Why this did you choose this liceance by mistake ?

**Comment by smackrajue** [comment]
Hi 
Sorry for the delay in responding here. You can get all the details here from our website. 
https://www.joforce.com/credits.html
https://www.joforce.com/terms-of-use.html
https://www.joforce.com/joforce-public-license.html
You cant remove included licenses, credits, and powered by text in the footer. If you have any questions contact us through https://www.joforce.com/support.html
Thanks
