### ISSUE TITLE
no info on how to set up cron for scheduler

### ISSUE THREAD

**Issue by rioshaz** [joforce/JoforceCRM#120]
please share step by step guide ....n cron command sample..

**Comment by smackrajue** [comment]
Cron tab entry sample
`15 * * * * sh /opt/vhost/abc.xyz.com/crm/cron/vtigercron.sh
`
Also you can refer the detailed documentation here
https://www.joforce.com/documentation/automation/scheduler
https://www.joforce.com/documentation/joforce-quickbooks-integration/help-tips
