### ISSUE TITLE
Demo not working 

### ISSUE THREAD

**Issue by rioshaz** [joforce/JoforceCRM#122]
when clicking on the notification in the demo.. its shows wierd blue top color menu..

![image](https://user-images.githubusercontent.com/54880467/101898982-0f8d7880-3bd3-11eb-8250-451be9712b58.png)

**Comment by smackrajue** [comment]
This is a public demo and users may try different settings of their own. It should be restored back periodically, now the demo is restored back to normal. You can try now, if you have any issue you can contact us to get restored
