### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by kkakko** [joforce/JoforceCRM#123]
When installing with xampp-windows-x64-7.2.34-2-VC15-installer, or even on the server I get the same message and do not install.

```
Warning: Declaration of AntlrLexer::matchAny() should be compatible with BaseRecognizer::matchAny($input) in C:\xampp\htdocs\joforce\libraries\antlr\AntlrLexer.php on line 297

Warning: Declaration of AntlrLexer::recover($re) should be compatible with BaseRecognizer::recover($input, $re) in C:\xampp\htdocs\joforce\libraries\antlr\AntlrLexer.php on line 297

Warning: Declaration of AntlrLexer::traceIn($ruleName, $ruleIndex) should be compatible with BaseRecognizer::traceIn($ruleName, $ruleIndex, $inputSymbol) in C:\xampp\htdocs\joforce\libraries\antlr\AntlrLexer.php on line 297

Warning: Declaration of AntlrLexer::traceOut($ruleName, $ruleIndex) should be compatible with BaseRecognizer::traceOut($ruleName, $ruleIndex, $inputSymbol) in C:\xampp\htdocs\joforce\libraries\antlr\AntlrLexer.php on line 297

Warning: Declaration of AntlrParser::traceIn($ruleName, $ruleIndex) should be compatible with BaseRecognizer::traceIn($ruleName, $ruleIndex, $inputSymbol) in C:\xampp\htdocs\joforce\libraries\antlr\AntlrParser.php on line 98

Warning: Declaration of AntlrParser::traceOut($ruleName, $ruleIndex) should be compatible with BaseRecognizer::traceOut($ruleName, $ruleIndex, $inputSymbol) in C:\xampp\htdocs\joforce\libraries\antlr\AntlrParser.php on line 98

Warning: Declaration of Users::saveentity($module) should be compatible with CRMEntity::saveentity($module, $fileid = '') in C:\xampp\htdocs\joforce\modules\Users\Users.php on line 1963

Warning: Declaration of Users::uploadAndSaveFile($id, $module, $file_details) should be compatible with CRMEntity::uploadAndSaveFile($id, $module, $file_details, $attachmentType = 'Attachment') in C:\xampp\htdocs\joforce\modules\Users\Users.php on line 1963

Warning: Declaration of Users::insertIntoEntityTable($table_name, $module) should be compatible with CRMEntity::insertIntoEntityTable($table_name, $module, $fileid = '') in C:\xampp\htdocs\joforce\modules\Users\Users.php on line 1963

Warning: Declaration of Users::save($module_name) should be compatible with CRMEntity::save($module_name, $fileid = '') in C:\xampp\htdocs\joforce\modules\Users\Users.php on line 1963

Warning: Declaration of Users::get_column_value($columname, $fldvalue, $fieldname, $uitype, $datatype) should be compatible with CRMEntity::get_column_value($columnname, $fldvalue, $fieldname, $uitype, $datatype = '') in C:\xampp\htdocs\joforce\modules\Users\Users.php on line 1963

Notice: Undefined variable: mod_strings in C:\xampp\htdocs\joforce\modules\CustomView\CustomView.php on line 18

Notice: Undefined variable: mod_strings in C:\xampp\htdocs\joforce\modules\CustomView\CustomView.php on line 19

Notice: Undefined variable: mod_strings in C:\xampp\htdocs\joforce\modules\CustomView\CustomView.php on line 20

Notice: Undefined variable: mod_strings in C:\xampp\htdocs\joforce\modules\CustomView\CustomView.php on line 21

Notice: Undefined variable: mod_strings in C:\xampp\htdocs\joforce\modules\CustomView\CustomView.php on line 22

Notice: Undefined variable: mod_strings in C:\xampp\htdocs\joforce\modules\CustomView\CustomView.php on line 23

Notice: Undefined variable: mod_strings in C:\xampp\htdocs\joforce\modules\CustomView\CustomView.php on line 24

Notice: Undefined variable: mod_strings in C:\xampp\htdocs\joforce\modules\CustomView\CustomView.php on line 25

Notice: Undefined variable: mod_strings in C:\xampp\htdocs\joforce\modules\CustomView\CustomView.php on line 26

Notice: Undefined variable: mod_strings in C:\xampp\htdocs\joforce\modules\CustomView\CustomView.php on line 27

Notice: Undefined variable: mod_strings in C:\xampp\htdocs\joforce\modules\CustomView\CustomView.php on line 28

Notice: Undefined variable: mod_strings in C:\xampp\htdocs\joforce\modules\CustomView\CustomView.php on line 29

Notice: Undefined variable: mod_strings in C:\xampp\htdocs\joforce\modules\CustomView\CustomView.php on line 30

Notice: Undefined variable: site_URL in C:\xampp\htdocs\joforce\routes.php on line 4

Warning: session_id(): Cannot change session id when headers already sent in C:\xampp\htdocs\joforce\libraries\HTTP_Session2\HTTP\Session2.php on line 324

Warning: session_start(): Cannot start session when headers already sent in C:\xampp\htdocs\joforce\libraries\HTTP_Session2\HTTP\Session2.php on line 211

Warning: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\joforce\modules\CustomView\CustomView.php:26) in C:\xampp\htdocs\joforce\includes\main\WebUI.php on line 183
```

**Comment by kkakko** [comment]
If I install with Laravel with:
display_errors = Off
I get this message:
MySQL Server should be configured with:
sql_mode = ERROR_FOR_DIVISION_BY_ZERO, NO_AUTO_CREATE_USER, NO_ENGINE_SUBSTITUTION

Put myself
display_errors = On
I get this message:
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; RecurringType has a deprecated constructor in C:\laragon\www\joforce\includes\utils\RecurringType.php on line 17

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; vt_DateTime has a deprecated constructor in C:\laragon\www\joforce\modules\Calendar\Date.php on line 13

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Tracker has a deprecated constructor in C:\laragon\www\joforce\data\Tracker.php on line 37

Warning: Declaration of AntlrLexer::matchAny() should be compatible with BaseRecognizer::matchAny($input) in C:\laragon\www\joforce\libraries\antlr\AntlrLexer.php on line 297

Warning: Declaration of AntlrLexer::recover($re) should be compatible with BaseRecognizer::recover($input, $re) in C:\laragon\www\joforce\libraries\antlr\AntlrLexer.php on line 297

Warning: Declaration of AntlrLexer::traceIn($ruleName, $ruleIndex) should be compatible with BaseRecognizer::traceIn($ruleName, $ruleIndex, $inputSymbol) in C:\laragon\www\joforce\libraries\antlr\AntlrLexer.php on line 297

Warning: Declaration of AntlrLexer::traceOut($ruleName, $ruleIndex) should be compatible with BaseRecognizer::traceOut($ruleName, $ruleIndex, $inputSymbol) in C:\laragon\www\joforce\libraries\antlr\AntlrLexer.php on line 297

Warning: Declaration of AntlrParser::traceIn($ruleName, $ruleIndex) should be compatible with BaseRecognizer::traceIn($ruleName, $ruleIndex, $inputSymbol) in C:\laragon\www\joforce\libraries\antlr\AntlrParser.php on line 98

Warning: Declaration of AntlrParser::traceOut($ruleName, $ruleIndex) should be compatible with BaseRecognizer::traceOut($ruleName, $ruleIndex, $inputSymbol) in C:\laragon\www\joforce\libraries\antlr\AntlrParser.php on line 98

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; ListViewSession has a deprecated constructor in C:\laragon\www\joforce\includes\ListView\ListViewSession.php on line 15

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; CustomView has a deprecated constructor in C:\laragon\www\joforce\modules\CustomView\CustomView.php on line 33

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Users has a deprecated constructor in C:\laragon\www\joforce\modules\Users\Users.php on line 43

Warning: Declaration of Users::saveentity($module) should be compatible with CRMEntity::saveentity($module, $fileid = '') in C:\laragon\www\joforce\modules\Users\Users.php on line 1963

Warning: Declaration of Users::uploadAndSaveFile($id, $module, $file_details) should be compatible with CRMEntity::uploadAndSaveFile($id, $module, $file_details, $attachmentType = 'Attachment') in C:\laragon\www\joforce\modules\Users\Users.php on line 1963

Warning: Declaration of Users::insertIntoEntityTable($table_name, $module) should be compatible with CRMEntity::insertIntoEntityTable($table_name, $module, $fileid = '') in C:\laragon\www\joforce\modules\Users\Users.php on line 1963

Warning: Declaration of Users::save($module_name) should be compatible with CRMEntity::save($module_name, $fileid = '') in C:\laragon\www\joforce\modules\Users\Users.php on line 1963

Warning: Declaration of Users::get_column_value($columname, $fldvalue, $fieldname, $uitype, $datatype) should be compatible with CRMEntity::get_column_value($columnname, $fldvalue, $fieldname, $uitype, $datatype = '') in C:\laragon\www\joforce\modules\Users\Users.php on line 1963

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; UserTimeZones has a deprecated constructor in C:\laragon\www\joforce\modules\Users\UserTimeZonesArray.php on line 16

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; EntityMeta has a deprecated constructor in C:\laragon\www\joforce\includes\Webservices\EntityMeta.php on line 12

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; HeadWebserviceObject has a deprecated constructor in C:\laragon\www\joforce\includes\Webservices\HeadWebserviceObject.php on line 12

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; HeadCRMObject has a deprecated constructor in C:\laragon\www\joforce\includes\Webservices\HeadCRMObject.php on line 12

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; HeadCRMObjectMeta has a deprecated constructor in C:\laragon\www\joforce\includes\Webservices\HeadCRMObjectMeta.php on line 12

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; WebServiceException has a deprecated constructor in C:\laragon\www\joforce\includes\Webservices\WebServiceError.php on line 13

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; WebserviceEntityOperation has a deprecated constructor in C:\laragon\www\joforce\includes\Webservices\WebserviceEntityOperation.php on line 12

Notice: Undefined variable: mod_strings in C:\laragon\www\joforce\modules\CustomView\CustomView.php on line 18

Notice: Undefined variable: mod_strings in C:\laragon\www\joforce\modules\CustomView\CustomView.php on line 19

Notice: Undefined variable: mod_strings in C:\laragon\www\joforce\modules\CustomView\CustomView.php on line 20

Notice: Undefined variable: mod_strings in C:\laragon\www\joforce\modules\CustomView\CustomView.php on line 21

Notice: Undefined variable: mod_strings in C:\laragon\www\joforce\modules\CustomView\CustomView.php on line 22

Notice: Undefined variable: mod_strings in C:\laragon\www\joforce\modules\CustomView\CustomView.php on line 23

Notice: Undefined variable: mod_strings in C:\laragon\www\joforce\modules\CustomView\CustomView.php on line 24

Notice: Undefined variable: mod_strings in C:\laragon\www\joforce\modules\CustomView\CustomView.php on line 25

Notice: Undefined variable: mod_strings in C:\laragon\www\joforce\modules\CustomView\CustomView.php on line 26

Notice: Undefined variable: mod_strings in C:\laragon\www\joforce\modules\CustomView\CustomView.php on line 27

Notice: Undefined variable: mod_strings in C:\laragon\www\joforce\modules\CustomView\CustomView.php on line 28

Notice: Undefined variable: mod_strings in C:\laragon\www\joforce\modules\CustomView\CustomView.php on line 29

Notice: Undefined variable: mod_strings in C:\laragon\www\joforce\modules\CustomView\CustomView.php on line 30

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; RelatedListViewSession has a deprecated constructor in C:\laragon\www\joforce\includes\ListView\RelatedListViewSession.php on line 20

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Head_Package has a deprecated constructor in C:\laragon\www\joforce\vtlib\Head\Package.php on line 17

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Head_PackageUpdate has a deprecated constructor in C:\laragon\www\joforce\vtlib\Head\PackageUpdate.php on line 17

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Head_PackageImport has a deprecated constructor in C:\laragon\www\joforce\vtlib\Head\PackageImport.php on line 21

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Head_PackageExport has a deprecated constructor in C:\laragon\www\joforce\vtlib\Head\PackageExport.php on line 20

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; dZip has a deprecated constructor in C:\laragon\www\joforce\vtlib\thirdparty\dZip.inc.php on line 8

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; dUnzip2 has a deprecated constructor in C:\laragon\www\joforce\vtlib\thirdparty\dUnzip2.inc.php on line 72

Notice: Undefined variable: site_URL in C:\laragon\www\joforce\routes.php on line 4

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; PEAR has a deprecated constructor in C:\laragon\www\joforce\vtlib\thirdparty\network\PEAR.php on line 102

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; PEAR_Error has a deprecated constructor in C:\laragon\www\joforce\vtlib\thirdparty\network\PEAR.php on line 826

Warning: session_start(): Cannot start session when headers already sent in C:\laragon\www\joforce\libraries\HTTP_Session2\HTTP\Session2.php on line 211

Warning: session_start(): Cannot start session when headers already sent in C:\laragon\www\joforce\libraries\csrf-magic\csrf-magic.php on line 378
Invalid request

**Comment by rioshaz** [comment]
no one wil help u this is a dead project

**Comment by smackrajue** [comment]
@kkakko Try these settings, it should work

Set `display_errors = Off`

// disable the strict mode of the Mysql for the best performance of Joforce 

`set sql_mode  = ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`

If you need any more help you can also contact us through https://www.joforce.com/contact-us.html
