### ISSUE TITLE
Upgrading Mobile module

### ISSUE THREAD

**Issue by rajbravo** [joforce/JoForceCRM#14]
Upgrading Mobile module to support Documents handling

**Comment by Lucipher** [comment]
@rajbravo Mobile Module for Native APP or H5 APP?

**Comment by fenzik** [comment]
@Lucipher Mobile module is to support the new JoForce mobile app

You can download the mobiles in 
https://play.google.com/store/apps/details?id=com.smackcoders.joforce
https://itunes.apple.com/us/app/joforce-crm/id1316384735?ls=1&mt=8

Ref: https://www.joforce.com/mobile-app.html
