### ISSUE TITLE
Can we use vtiger extensions?

### ISSUE THREAD

**Issue by ugintl** [joforce/JoforceCRM#143]
Can we use vtiger extensions?

**Comment by muthukumarsupport** [comment]
Hi,

Vtiger extensions cannot be installed on the JoforCRM system.

JoforCRM extensions list are available in the below link
https://www.joforce.com/products.html

If anyone of the module matches your requirements, please go ahead and complete the purchase.

Let me know if you need any clarifications before purchase.

Thanks.
