### ISSUE TITLE
project tasks don't show up in the project task list

### ISSUE THREAD

**Issue by tehnomage** [joforce/JoforceCRM#144]
this is for joForce 1.5

basically, we've added a project and then some tasks associated with this project but even though there are no errors when adding them they don't show up when you go to the Project > Project Tasks.

They are however viewable from Inventory > Project Tasks.

Any suggestions on how to fix this?

**Comment by subbulakshmie** [comment]
@tehnomage Issue fixed and committed in Joforce1.5.
