### ISSUE TITLE
1 issue 1 question warehouse or storage

### ISSUE THREAD

**Issue by robygladio** [joforce/JoforceCRM#16]
hello, 

Question
do you plan to add a basic storage system?  just to manage the products quantity balance buy and sell using product code and serial no.  
is a CRM so basic storage will be enough making a document of sales or shipment discharging quantity from warehouse.

ISSUE
Linux + Xampp 5.6 instllation issue. index.php. 
It's seam multiple error but i believe is just a wrong link that get many error. permission to file and folders is 777 no ssl implemented.  Is a local server just to test. 

Notice: Undefined variable: mod_strings in /opt/lampp/htdocs/joforce2/modules/CustomView/CustomView.php on line 18

Notice: Undefined variable: mod_strings in /opt/lampp/htdocs/joforce2/modules/CustomView/CustomView.php on line 19

Notice: Undefined variable: mod_strings in /opt/lampp/htdocs/joforce2/modules/CustomView/CustomView.php on line 20

Notice: Undefined variable: mod_strings in /opt/lampp/htdocs/joforce2/modules/CustomView/CustomView.php on line 21

Notice: Undefined variable: mod_strings in /opt/lampp/htdocs/joforce2/modules/CustomView/CustomView.php on line 22

Notice: Undefined variable: mod_strings in /opt/lampp/htdocs/joforce2/modules/CustomView/CustomView.php on line 23

Notice: Undefined variable: mod_strings in /opt/lampp/htdocs/joforce2/modules/CustomView/CustomView.php on line 24

Notice: Undefined variable: mod_strings in /opt/lampp/htdocs/joforce2/modules/CustomView/CustomView.php on line 25

Notice: Undefined variable: mod_strings in /opt/lampp/htdocs/joforce2/modules/CustomView/CustomView.php on line 26

Notice: Undefined variable: mod_strings in /opt/lampp/htdocs/joforce2/modules/CustomView/CustomView.php on line 27

Notice: Undefined variable: mod_strings in /opt/lampp/htdocs/joforce2/modules/CustomView/CustomView.php on line 28

Notice: Undefined variable: mod_strings in /opt/lampp/htdocs/joforce2/modules/CustomView/CustomView.php on line 29

Notice: Undefined variable: mod_strings in /opt/lampp/htdocs/joforce2/modules/CustomView/CustomView.php on line 30

Notice: Undefined index: action in /opt/lampp/htdocs/joforce2/include/utils/utils.php on line 343

Notice: Undefined index: language in /opt/lampp/htdocs/joforce2/includes/runtime/BaseModel.php on line 32

Notice: Undefined index: language in /opt/lampp/htdocs/joforce2/includes/runtime/BaseModel.php on line 32

Notice: Undefined index: action in /opt/lampp/htdocs/joforce2/include/utils/ListViewUtils.php on line 679

Notice: Undefined index: file in /opt/lampp/htdocs/joforce2/include/utils/ListViewUtils.php on line 679

Notice: Undefined variable: recordName in /opt/lampp/htdocs/joforce2/includes/runtime/Controller.php on line 143

Notice: Undefined index: language in /opt/lampp/htdocs/joforce2/includes/runtime/BaseModel.php on line 32

Notice: Undefined index: language in /opt/lampp/htdocs/joforce2/includes/runtime/BaseModel.php on line 32

Notice: Undefined index: action in /opt/lampp/htdocs/joforce2/include/utils/ListViewUtils.php on line 679

Notice: Undefined index: file in /opt/lampp/htdocs/joforce2/include/utils/ListViewUtils.php on line 679

Notice: Undefined index: language in /opt/lampp/htdocs/joforce2/includes/runtime/BaseModel.php on line 32

Notice: Undefined index: theme in /opt/lampp/htdocs/joforce2/includes/runtime/BaseModel.php on line 32

Notice: Undefined index: language in /opt/lampp/htdocs/joforce2/includes/runtime/BaseModel.php on line 32

Notice: Undefined index: language in /opt/lampp/htdocs/joforce2/includes/runtime/BaseModel.php on line 32

Notice: Undefined index: V7_THEME_PATH in /opt/lampp/htdocs/joforce2/test/templates_c/2e1477552c00acce1aedaa8e55bee88a9b67fc38.file.Header.tpl.php on line 40

Notice: Trying to get property of non-object in /opt/lampp/htdocs/joforce2/test/templates_c/2e1477552c00acce1aedaa8e55bee88a9b67fc38.file.Header.tpl.php on line 40

Notice: Undefined index: language in /opt/lampp/htdocs/joforce2/includes/runtime/BaseModel.php on line 32

Notice: Undefined index: action in /opt/lampp/htdocs/joforce2/include/utils/ListViewUtils.php on line 679

Notice: Undefined index: file in /opt/lampp/htdocs/joforce2/include/utils/ListViewUtils.php on line 679
Installation Wizard

Notice: Undefined index: language in /opt/lampp/htdocs/joforce2/includes/runtime/BaseModel.php on line 32

Notice: Undefined index: action in /opt/lampp/htdocs/joforce2/include/utils/ListViewUtils.php on line 679

Notice: Undefined index: file in /opt/lampp/htdocs/joforce2/include/utils/ListViewUtils.php on line 679
Welcome

Head Logo

Notice: Undefined index: language in /opt/lampp/htdocs/joforce2/includes/runtime/BaseModel.php on line 32

Notice: Undefined index: action in /opt/lampp/htdocs/joforce2/include/utils/ListViewUtils.php on line 679

Notice: Undefined index: file in /opt/lampp/htdocs/joforce2/include/utils/ListViewUtils.php on line 679
Welcome to JoForce Setup Wizard

Notice: Undefined index: language in /opt/lampp/htdocs/joforce2/includes/runtime/BaseModel.php on line 32

Notice: Undefined index: action in /opt/lampp/htdocs/joforce2/include/utils/ListViewUtils.php on line 679

Notice: Undefined index: file in /opt/lampp/htdocs/joforce2/include/utils/ListViewUtils.php on line 679
This wizard will guide you through the installation of JoForce
<br /><b>Notice</b>: Undefined index: language in <b>/opt/lampp/htdocs/joforce2/includes/runtime/BaseModel.php</b> on line <b>32</b><br /><br /><b>Notice</b>: Undefined index: action in <b>/opt/lampp/htdocs/joforce2/include/utils/ListViewUtils.php</b> on line <b>679</b><br /><br /><b>Notice</b>: Undefined index: file in <b>/opt/lampp/htdocs/joforce2/include/utils/ListViewUtils.php</b> on line <b>679</b><br />Install

Notice: Undefined index: language in /opt/lampp/htdocs/joforce2/includes/runtime/BaseModel.php on line 32

Notice: Undefined index: action in /opt/lampp/htdocs/joforce2/include/utils/ListViewUtils.php on line 679

Notice: Undefined index: file in /opt/lampp/htdocs/joforce2/include/utils/ListViewUtils.php on line 679
Powered by JoForce © 2017

thank you
Roberto

**Comment by rajbravo** [comment]
@robygladio,
Right now, we don't have any plan to add Warehouse module.
