### ISSUE TITLE
BUG?: no edit purchase order from products folder

### ISSUE THREAD

**Issue by robygladio** [joforce/JoForceCRM#17]
VERSION
$patch_version = '20170605'; // -ve timestamp before release, +ve timestamp after release.
$modified_database = '';
$jo_current_version = '7.0.1';

http://192.168.1.7/joforce2//Products/PurchaseOrder/Detail/2/showRelatedList/41/Purchase%20Order/INVENTORY

if I try to click on pen icon (edit) do nothing 
if you click in any part of row of purchase order for a specific product open a dashboard empty 
(clicking on more right high, give LBL_ADD_NEW_DASHBOARD or Rearrange TABS) no other option available. 

If I clikc on purchase order from this window
http://192.168.1.7/joforce2/PurchaseOrder/List/INVENTORY

then I have eye to look and work
i can clik and go to detailed purchase order then click on EDIT it's working perfectly.

**Comment by LakshmiSR** [comment]
The issue is fixed in this latest version. Kindly check it out.
