### ISSUE TITLE
Commercial Use

### ISSUE THREAD

**Issue by ugintl** [joforce/JoforceCRM#180]
I went through the license, but I am still confused. Are there any restrictions of using it for commercial purposes? Installing it for a client is another thing. My question is that is it allowed to build a customized product out of this code and then sell it as my own?

**Comment by smackrajue** [comment]
Kindly verify the license under sections 2.2.a & 13 for clarification. Commercial term is limited and selling as a product bundle is not allowed or authorized.

**Comment by ugintl** [comment]
ok thanks
