### ISSUE TITLE
google error 500

### ISSUE THREAD

**Issue by robygladio** [joforce/JoForceCRM#19]
http://192.168.1.7/joforce2/index.php?module=Google&view=List&operation=sync&sourcemodule=Contacts

version 1 get error 500 
version 1.2 master get blank pop up page

error refer to:
cal dav and contact module

**Comment by fenzik** [comment]
@robygladio This is will be fixed in the next version this month.

**Comment by LakshmiSR** [comment]
@robygladio Issue fixed in the latest version.
