### ISSUE TITLE
Hi developer

### ISSUE THREAD

**Issue by centoasa** [joforce/JoforceCRM#20]
I would transfer my vtiger crm to yours, but I would to know something:
1. whats the very difference from vtiger?
2. have the same issue/difficult by vtiger (cron doesn't work if not change code into cron.php, portal send always ***** as password recovery and so on...)
3. pdf manager?
4. italian language as vtiger?
5: portal?
Thank you

**Comment by robygladio** [comment]
it's seam they stop to develop :(

**Comment by rajkumargohan** [comment]
Hi @centoasa 

- Differences can be seen on this blog - https://www.joforce.com/blog/2017/08/03/roadmap-for-upcoming-versions/
- PDF Maker is installed by default. 
- Currently, we are not providing an option to add new modules.
- If you find out any issue, you can raise a ticket here which will be resolved soon and updated. Contributions are much appreciated.

**Comment by centoasa** [comment]
@rajkumargohan Thank you so much

**Comment by centoasa** [comment]
Which languages ​​are available at the installation?

**Comment by centoasa** [comment]
Strange, because on user setting I've found the italian, and almost all the parts of Joforce are translated.

**Comment by centoasa** [comment]
@robygladio Sono italiano, e potremmo contribuire al miglioramento di questo crm.

**Comment by rajbravo** [comment]
@centoasa On Installation page alone, we didn't add Language support.

**Comment by rajbravo** [comment]
@centoasa Contributions are welcome 👍

**Comment by centoasa** [comment]
![schermata 2017-12-04 alle 12 04 36](https://user-images.githubusercontent.com/5500935/33549592-557efb00-d8eb-11e7-8004-60ee8a7d27a6.png)
![schermata 2017-12-04 alle 12 05 37](https://user-images.githubusercontent.com/5500935/33549625-74c48174-d8eb-11e7-9c71-10b5bc29f582.png)
my Joforce now is in italian language

**Comment by robygladio** [comment]
Most translation is made. 
only few things are left.
Is my language i can provide for the left translation. 
IMO the most important is the pdf make to print invoice in European format in the right language.

**Comment by fenzik** [comment]
@robygladio Thank you for the contribution, we'll implement it in the next version and make sure it work perfectly in the PDFs
