### ISSUE TITLE
pdf

### ISSUE THREAD

**Issue by centoasa** [joforce/JoForceCRM#22]
When I try to generate pdf by purchase ordine https://crm.100asa.it/PurchaseOrder/ExportPDF/19/INVENTORY the page is blank
When try to send attachments, Joforce stuck.

**Comment by fenzik** [comment]
> When I try to generate pdf by purchase ordine https://crm.100asa.it/PurchaseOrder/ExportPDF/19/INVENTORY the page is blank
When try to send attachments, Joforce stuck.

Kindly provide the following information

1. Php error log. 
2. Operating system with version.
3. Php & mysql version

**Comment by centoasa** [comment]
apache php 7.0.25
mysqlnd 5.0.12
error log for my ph is disabled

**Comment by LakshmiSR** [comment]
Issue fixed in the latest version. Kindly check it out.
