### ISSUE TITLE
Problems saving custom modules

### ISSUE THREAD

**Issue by moabin** [joforce/JoForceCRM#26]
I'm having multiple problems with custom modules.
Sometime Ill try to install a new module and there's no response. But the module is created but not accessible via the menu. Some will have database tables created but others will not.
Its hit and miss getting the entry added to jo_ws_entity table as well.
Trying to update a module also doesnt work reliably.
We have been reduced to doing a module once (never changing it) on a dev instance and downloading zip to install into a separate instance of Joforce. 
Does anyone have a bulletproof way to create custom modules?

**Comment by LakshmiSR** [comment]
Issue fixed in the latest version. Kindly try it out.
