### ISSUE TITLE
1.3 blank screen after installation

### ISSUE THREAD

**Issue by francoisvandermerwe** [joforce/JoForceCRM#28]
Hi ive been struggling to setup 1.2 & 1.3 now installation works 100% parameters are correct.
With 1.2 I get to a point where I can log in  the A) it either doesn't accept my Credentials or B) I get past login point and have to setup time/ currency etc currencies / time settings are there in the dropdowns during installation but nothing when I setup, I checked db and those tables are also blank? as for 1.3 installation finishes, get to a blank page cant reach joforce1.3 keeps refreshing but nothing ever happens. 
my php.ini settings are correct and all the checks and versions of wamp /MySQL php etc is correct. please help this is urgent.

**Comment by francoisvandermerwe** [comment]
edit: I get a Joforce login screen now , but it doesn't accept my credentials, which I know is  correct. is it not writing to db whats going on here ?privilege issue ?

**Comment by rajbravo** [comment]
Can you enable error_reporting and share the log?

Can you make sure mod_rewrite is enabled on your machine?

**Comment by francoisvandermerwe** [comment]
re-installing atm ,it also gives you no option to create the database, you have to create it first then point the install to the db.. will enable error_reporting and share the log in a couple of minutes. 
LoadModule rewrite_module modules/mod_rewrite.so is on..

**Comment by rajbravo** [comment]
Is it possible to share your ssh details to support@joforce.com?
We will have a look and let you know.

**Comment by francoisvandermerwe** [comment]
I Am running on windows 10 with a wamp server..only option teamview/vnc etc ?
