### ISSUE TITLE
Blank popup when on showrelatedlist

### ISSUE THREAD

**Issue by moabin** [joforce/JoForceCRM#29]
For example when I click on an Organisation I see many related tabs. If I click on the contacts i get list of related contacts.
If I try to click one of those contacts to view the contact I get a blank mid screen popup of the empty dashboard.
This behavior is the same for any built in or custom module..the related list tab shows the items but I cannot view that item by clicking on it.

List of contacts:
![image](https://user-images.githubusercontent.com/32509579/38718770-e85dffac-3eee-11e8-93d3-8727c1de3dbc.png)

Trying to click on a Contact to view:
![image](https://user-images.githubusercontent.com/32509579/38718777-f904cdea-3eee-11e8-8e39-263fa462d907.png)

I can inspect  the row and it looks like this:
`<tr class="listViewEntries" data-id="3" data-recordurl="http://localhost/dactcrm/Contacts/Detail/3"><td class="related-list-actions"><span class="actionImages">&nbsp;&nbsp;&nbsp;<a name="relationEdit" data-url="http://localhost/dactcrm/index.php?module=Contacts&amp;view=Edit&amp;record=3"><i title="Edit" class="fa fa-pencil"></i></a> &nbsp;&nbsp;<a class="relationDelete"><i title="Unlink" class="vicon-linkopen"></i></a></span></td><td class="relatedListEntryValues" title="" data-field-type="phone" nowrap=""><span class="value textOverflowEllipsis"></span></td><td class="relatedListEntryValues" title="thaboz@gmail.com" data-field-type="email" nowrap=""><span class="value textOverflowEllipsis"><a class="emailField cursorPointer" onclick="Head_Helper_Js.getInternalMailer(3,'email','Contacts');">thaboz@gmail.com</a></span></td><td class="relatedListEntryValues" title="" data-field-type="string" nowrap=""><span class="value textOverflowEllipsis"></span></td><td class="relatedListEntryValues" title="Thabo" data-field-type="salutation" nowrap=""><span class="value textOverflowEllipsis">Thabo</span></td><td class="relatedListEntryValues" title="Zumani" data-field-type="string" nowrap=""><span class="value textOverflowEllipsis">Zumani</span></td><td class="relatedListEntryValues" title="Thosim Construction" data-field-type="reference" nowrap=""><span class="value textOverflowEllipsis"><a href="index.php?module=Accounts&amp;view=Detail&amp;record=2" title="Organization Name:Thosim Construction" data-original-title="Organizations">Thosim Construction</a></span></td><td class="relatedListEntryValues" title="" data-field-type="string" nowrap=""><span class="value textOverflowEllipsis"></span></td><td class="relatedListEntryValues" title="Marketing Group" data-field-type="owner" nowrap=""><span class="value textOverflowEllipsis"><a href="http://localhost/dactcrm/Groups/Settings/Detail/3">Marketing Group</a></span></td><td class="relatedListEntryValues" title="" data-field-type="string" nowrap=""><span class="value textOverflowEllipsis"></span></td><td class="relatedListEntryValues" title="" data-field-type="string" nowrap=""><span class="value textOverflowEllipsis"></span></td><td class="relatedListEntryValues" title="CON1" data-field-type="string" nowrap=""><span class="value textOverflowEllipsis"><a href="http://localhost/dactcrm/Contacts/Detail/3">CON1</a></span></td></tr>`

**Comment by moabin** [comment]
seems to be this link that is trying to be shown:

http://localhost/joforce/index.php?mode=showDetailViewByMode&requestMode=full&displayMode=overlay

**Comment by LakshmiSR** [comment]
@moabin Currently you're using the older version of JoForce. Kindly try out the latest version JoForce1.3, where all these issues are resolved.

**Comment by moabin** [comment]
I did play around with the new version but some of my custom modules with related links to other custom modules failed to load correctly in studio...I can see them on Modules, but not in menu...

I'm also in the middle of development cycle and worried about the client seeing a brand new interface...but I will have to go the route of porting to the upgraded version and hopefully I can overcome my custom module issues.
I did verify that my issue is indeed fixed in newest version.
