### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [joforce/JoForceCRM#30]
Hello, 
we're trying to install your system and we get the following error message:
![instalator](https://user-images.githubusercontent.com/10218164/39243642-73d07a08-488e-11e8-9c4a-6b428dedcc6a.png)
We would appreciate your advice.

**Comment by LakshmiSR** [comment]
Hi,
Kindly let us know when you're getting this error message (i.e. during which step of your installation process). This will help us to reproduce it.

**Comment by KatarzynaUlichnowska** [comment]
Straight away when we enter the address where the CRM is.
We downloaded it from GitHub and from your website - the same in both cases.

**Comment by LakshmiSR** [comment]
Okay. Shall we connect via Team viewer at your convenient time? Kindly share us your credentials via email - support@joforce.com

**Comment by mariuszkrzaczkowski** [comment]
Please specify the configuration requirements, we tested on PHP 5.6 and 7.1 and it does not work.

**Comment by LakshmiSR** [comment]
Below is the configuration requirements
Apache - 2.4
MYSQL- 5.6
PHP - 5.6, 7.0.1
Kindly tell us your configuration setup, we will try to reproduce the same in our local server.

**Comment by mariuszkrzaczkowski** [comment]
Wampserver
Apache - 2.4.29
MariaDB - 10.2.13
PHP - 5.6

**Comment by LakshmiSR** [comment]
JoForce CRM currently works with MySQL database. We will consider adding the support for Maria DB in our future update. Now, kindly try with the MySQL database.
