### ISSUE TITLE
PDF Maker not working

### ISSUE THREAD

**Issue by Naholiel** [joforce/JoForceCRM#33]
Hi,

I recently installed joforce and everything seems to works fine except for PDF Maker. 

I can access the list of PDF template but I can't edit them (when I click on edit, it only displays a blank page). Also, when I try to export as PDF, it returns an error "File not found".

I checked php and nginx error log and none of them got any problem.

Configuration :
Debian 8
Nginx
php7.1

I link a screen of the display when clicking on edit. 

![joforce_blank_edit](https://user-images.githubusercontent.com/25816593/41529639-16b4b1b0-72ee-11e8-858a-dd1fe6d6cd6f.png)

**Comment by LakshmiSR** [comment]
Hi @Naholiel,
Kindly enable error_reporting and share us the eror_log. This will help us to debug and resolve the issue. 
To enable error_reporting,
1. Navigate to config.ini.php file in the config folder.
2. Un command the first two lines (ini_set)
3. Now refresh the page, you will get the error message.

**Comment by Naholiel** [comment]
Thank you for your response, but I don't have any file that correspond to "config.ini.php" in the config folder. 
I got one named "config.inc.php" but there is nothing in it.
 
This file being included by "config.php", I added this two lines 

> ini_set('display_errors', '1');
> ini_set('display_startup_errors', 1);

Then, I tried to edit a template and still no error being displayed. 


Can you please give me the correct lines to add to get the error message ?
