### ISSUE TITLE
PHP7 bug

### ISSUE THREAD

**Issue by Lucipher** [joforce/JoForceCRM#5]
Email Template, Email Plus,Pdf Maker not work.....

 Email Plus sever settings also not work on PHP5.5

Jquery warning.
jquery-migrate-1.0.0.js?v=7.0.1:29 JQMIGRATE: jQuery.fn.live() is deprecated

**Comment by fenzik** [comment]
@Lucipher Email Template, Email Plus and PDF Maker working.

jQuery warnings will be fixed in next version. Will create a new ticket for that

Please check and let us know. Re-open the ticket if you face any issues.
