### ISSUE TITLE
EmailTemplates error

### ISSUE THREAD

**Issue by Lucipher** [joforce/JoForceCRM#8]
EmailTemplate js error on listview
Index.js  jQuery(...).instaFilta is not a function

List:1208 Uncaught ReferenceError: _PAGEREADYAT is not defined
var _PAGEREADYTIME = _PAGEREADYAT.getTime() / 1000.0; // seconds

Can not edit  or add emailtemplate!

**Comment by Lucipher** [comment]
The same error on demo.joforce.com

**Comment by rajbravo** [comment]
@Lucipher Will fix the issue and let you know
