### ISSUE TITLE
joforce support

### ISSUE THREAD

**Issue by CasGomez** [joforce/JoForceCRM#86]
i love the demo but there is no support from you guys at all. the website doesn't work the media pages do not respond and all emails i send are ignored. i would love to make this crm my own but i have no idea how to my only issue is the level of support because there seems to be none

**Comment by LakshmiSR** [comment]
@CasGomez Sorry for the inconvenience. The website was in maintenance and now it is working. Can you please send your queries to hello@joforce.com.
