### ISSUE TITLE
1.4 version pbx management error

### ISSUE THREAD

**Issue by Lucipher** [joforce/JoForceCRM#87]
1.4 version pbx management blank page

**Comment by Lucipher** [comment]
DEBUG VT - Handler not found.:#0 /opt/jofoce/includes/main/WebUI.php(186): Head_Loader::getComponentClassName('View', 'index.php', 'Settings:PBXMan...')

**Comment by LakshmiSR** [comment]
@Lucipher 
As we're following up on this ticket - https://github.com/joforce/JoForceCRM/issues/88 
I'm closing this ticket.
