### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Lucipher** [joforce/JoForceCRM#89]
1. Add task set  "Sent Reminder" can not save the value.
2. Show blank page when click Event/Task on Month Calendar
3. Email Template edit  failure
4. PBX manager index select provider configuration error
5.  Quotes,Salesorder,Invoice row detail can not open in Organization/Contact Detail tab page

**Comment by Lucipher** [comment]
@LakshmiSR 
So far,is there any update?

**Comment by LakshmiSR** [comment]
@Lucipher - https://bit.ly/2Te8LKA
