### ISSUE TITLE
Error Reporting

### ISSUE THREAD

**Issue by dfanaei** [joforce/JoforceCRM#95]
Hi Again,
I am trying to properly install Joforce on my ubuntu 16.04 LTS server. All server settings are done properly, however, I am still seeing errors below above the page: 

```
Warning: Declaration of Users::saveentity($module) should be compatible with CRMEntity::saveentity($module, $fileid = '') in /var/www/html/crm/modules/Users/Users.php on line 0

Warning: Declaration of Users::uploadAndSaveFile($id, $module, $file_details) should be compatible with CRMEntity::uploadAndSaveFile($id, $module, $file_details, $attachmentType = 'Attachment') in /var/www/html/crm/modules/Users/Users.php on line 0

Warning: Declaration of Users::insertIntoEntityTable($table_name, $module) should be compatible with CRMEntity::insertIntoEntityTable($table_name, $module, $fileid = '') in /var/www/html/crm/modules/Users/Users.php on line 0

Warning: Declaration of Users::save($module_name) should be compatible with CRMEntity::save($module_name, $fileid = '') in /var/www/html/crm/modules/Users/Users.php on line 0

Warning: Declaration of Users::get_column_value($columname, $fldvalue, $fieldname, $uitype, $datatype) should be compatible with CRMEntity::get_column_value($columnname, $fldvalue, $fieldname, $uitype, $datatype = '') in /var/www/html/crm/modules/Users/Users.php on line 0
```

My Server info:
Ubuntu 16.0.4 LTS
Apache 2
PHP 7.1
Mysql (I think it is 5.7)

I have already changed the error_reporting to E_WARNING & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT in the php.ini, However, It is still saying NOT RECOMMENDED for my current settings. 

Can you please help me resolve this issue?
Thanks,

**Comment by Dinesh-JoForce** [comment]
Hi @dfanaei ,

I agree that you have turned off your Error_reporting in Php.ini File. However, it seems that you have not turned off in your config/config.inc.php. Once you turn off your error reporting in this file the errors wouldn't display.

I hope i have cleared your query.
